main: shyndard.spigot.util.footslime.FootSlimePlugin
name: FootSlime
version: "1.0.0"
description: FootSlime plugin for o2c
author: Shyndard
commands:
   footslime:
      aliases:
      - fs
      description: Footslime command
      usage: /<command> [start|end|score|list|select]